### ISSUE TITLE
Integrate Mockito into voclipse

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#37]
See http://stackoverflow.com/questions/18122834/which-dependencies-do-i-need-to-use-mockito-and-junit-in-an-eclipse-rcp-tycho-pr

I suggest you also add a section about Orbit to your thesis on the build tutorial of voclipse. Orbit hosts non Eclipse plug-ins which are OSGified.

**Comment by vogella** [comment]
Update site http://download.eclipse.org/tools/orbit/downloads/drops/I20140114130914/repository/

**Comment by vogella** [comment]
Plug-ins org.mockito and org.mockito.source

**Comment by vogella** [comment]
Strange. Their seem to be no feature for org.mockito available.

**Comment by hendrikstill** [comment]
It seems that every bundle in the orbit repository is a plug-in. Guess the problem is our feature based product.
Should we create a new feature like com.vogella.vde.developmenttools.feature (or something like that) where we can add plug-ins from the orbit repository? 

By the way, thanks for the help!

**Comment by vogella** [comment]
> Should we create a new feature like com.vogella.vde.developmenttools.feature
> (or something like that) where we can add plug-ins from the orbit
> repository?

+1, makes sense to separate our base plug-ins from other plug-ins.

2014/1/14 Hendrik S notifications@github.com

**Comment by vogella** [comment]
Fixed for now, I added Mochito to the existing vde feature , please open a new issue for the new feature.
