### ISSUE TITLE
voclipse based on outdated version

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.vde#70]
Looks like the aggregation in voclipse is broken, I see lots of "old" errors in there. For example the e4tools seems to be present in an older version:

0.12.0.v20140207 in voclipse
0.14.0.v20140207 über http://download.vogella.com/luna/e4tools

**Comment by vogella** [comment]
@hendrikstill this make currently the voclipse unsuable for me.

**Comment by hendrikstill** [comment]
At my installation the current version of the plug-in is 0.12.0 
and for the feature 0.14.0
Feature:
![e4_version_plugin](https://f.cloud.github.com/assets/374528/2125829/bba3ae40-9258-11e3-97b9-13da50a16fdb.png)
Plug-In:
![e4version_feature](https://f.cloud.github.com/assets/374528/2125830/bbc43b7e-9258-11e3-873b-a1da2d5f28e9.png)

From the build-side this is correct, because plug-in and feature of the e4 tools  declare different versions.
http://git.eclipse.org/c/e4/org.eclipse.e4.tools.git/tree/features/org.eclipse.e4.core.tools.feature/pom.xml#n13
http://git.eclipse.org/c/e4/org.eclipse.e4.tools.git/tree/bundles/org.eclipse.e4.tools/pom.xml#n13 

@vogella Can you specify the concrete problems?

**Comment by hendrikstill** [comment]
I think a better example is the org.eclipse.ui.ide plug-in which is version 3.10.0.v20140122-1109 and not the latest available form our cbi platform build 3.10.0.v20140130-2242. 

The installed plug-in comes from http://download.eclipse.org/releases/luna/ .
But I don't know why p2 does not use the newer version

![image](https://f.cloud.github.com/assets/374528/2126271/1cf82ae8-9260-11e3-8900-88cdbe2f5163.png)

**Comment by hendrikstill** [comment]
So as expected the P2 resolver is not able to "always use the newest bundle". [1]
This is also not a trivial problem, so I guess we have to minimize the count of bundles.

So my suggestion would be to remove the older bundles from the set of resolvable bundles.
[1]https://bugs.eclipse.org/bugs/show_bug.cgi?id=352560

**Comment by vogella** [comment]
Sounds good. I just run rm -rf on .m2/repository for this for the Jenkins build user, right?

**Comment by hendrikstill** [comment]
No, the problem is a little bit more complex.
Due to including the http://download.eclipse.org/releases/luna/  AND  http://download.vogella.com/p2/C-MASTER-eclipse.platform.releng.aggregator/lastStable/archive/eclipse.platform.releng.tychoeclipsebuilder/sdk/target/repository/ update sites as artifact-source to our build, we have a big set of available bundles.

Within this big set of available bundles p2 tries to resolve a smaller set of bundles which satisfies the dependencies given from (in our case) the product. 
The goal of p2 is only to find a correct set of bundles to handle the dependencies. 
If one dependency can be satisfies by different bundles of the big set of available bundles chooses on of theme by different criteria. The version number is just one of the criteria, so the algorithm can not assure that it selects only the newest  bundles.

My suggestion was to keep the "big set of available bundles" small and avoid to have different versions for a single bundle. 
One big step would be to remove the http://download.eclipse.org/releases/luna/ updatesite from the tycho build. But without this we will miss some bundles we depend on like emf, so we have to find updatesites which only supply the needed bundles.  In some cases this is easy in some not.
For example I haven't found a repository which only supplies <code>org.eclipse.wst.xml_ui.feature.feature.group</code> bundle

**Comment by vogella** [comment]
I think that is what a target platform is for, you can specify which
plugins are used from which p2 update side
Am 10.02.2014 17:14 schrieb "Hendrik S" notifications@github.com:

**Comment by hendrikstill** [comment]
I think we discussed that previously. 
As far as I understand the target platform is a final state of a set of bundles which helps to avoid  incompatibility  problems. 
Our set of bundles is non final and constantly changing. 
We have changing versions and changing amount of bundles in the set.

But to be fair, the fact, that I wasn't able to use a target platform to solve this problem, doesn't mean that it is impossible. 
One big problem was that the editor of the target platform simply does not support actions like removing version dependencies etc.

**Comment by vogella** [comment]
Would be nice if we can try the target definition file. According to
http://www.bsiag.com/scout/version0-0-0-in-target-platform/ 0.0.0 should
result in the latest and highest version number.

Also Tycho support filtering for target definition files, which could also
help here.

See https://wiki.eclipse.org/Tycho/Target_Platform or more specifically
https://wiki.eclipse.org/Tycho/Target_Platform#Filtering

2014-02-10 19:36 GMT+01:00 Hendrik S notifications@github.com:

**Comment by vogella** [comment]
Lets close this, should clear out once Luna repos get synchronized
